name = "youtube-transcript-api"
main = "index.ts"
compatibility_date = "2024-05-01"

# Add any bindings (KV, R2, D1, etc.) or environment variables here if needed in the future
# [vars]
# MY_VARIABLE = "example_value"

# Enable node_compat for libraries that might rely on Node.js built-in modules
node_compat = true
